Print an error message in CI for towncrier failures

diff --git a/.github/workflows/towncrier-run.yml b/.github/workflows/towncrier-run.yml
--- a/.github/workflows/towncrier-run.yml
+++ b/.github/workflows/towncrier-run.yml
@@ -67,4 +67,22 @@ jobs:
       run: python -m pip install ${{ inputs.tox-source }}
 
     - name: Run towncrier check
+      id: tox
       run: tox -e towncrier-check
+
+    - name: Towncrier Check Resolution Instructions
+      if: always() && steps.tox.outcome == 'failure'
+      run: |
+        echo
+        echo '::error::*************************************************************************'
+        echo '::error::** Towncrier check failed for missing change note                      **'
+        echo '::error::*************************************************************************'
+        echo '::error:: '
+        echo '::error::A change note for the PR is missing from the `changes` directory.'
+        echo '::error:: '
+        echo '::error::Visit the docs below to learn how to add a change note:'
+        echo '::error:: '
+        echo '::error::    https://beeware.org/contributing/how/process/'
+        echo '::error:: '
+        echo '::error::*************************************************************************'
+        exit 1
